### ISSUE TITLE
What encoding

### ISSUE THREAD

**Issue by evshiron** [doylecnn/cqpsdk-rust#2]
I use Sublime Text to compose Rust code, and it's nice when working with `UTF-8`, however applications in Windows use non-Unicode encoding.

I am thinking about including an `encoding` module to translate `UTF-8` to `cp936` when calling APIs, and our code sticks with `UTF-8`, any ideas?

**Comment by doylecnn** [comment]
这样比较好

**Comment by Coxxs** [comment]
嗯，在发出前转为酷Q需要的ANSI编码吧。酷Q内部已经全部是utf-8处理，未来也会提供utf-8接口。

**Comment by evshiron** [comment]
This issue should have been fixed in 44f1544 and 416b704. Cheers!
